In [9]:
import pandas as pd
import plotly.express as px
import numpy as np
import pathlib
from tqdm import tqdm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import svm

df = pd.read_csv("Datasets/PokerDataSet.csv", encoding="ISO-8859-1")
df = df.sample(20000, random_state=35)

print(df.head())

   V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  Class
0   3  12   3   2   3  11   4   5   2    5      2
1   1   9   4   6   1   4   3   2   3    9      2
2   1   4   3  13   2  13   2   1   3    6      2
3   3  10   2   7   1   2   2  11   4    9      1
4   1   3   4   5   3   4   1  12   4    6      1

In [15]:
categorized_df = df.iloc[:,[0,2,4,6,8]]
categorized_df
cat_1hot = pd.get_dummies(categorized_df.astype(str))
cat_1hot.head()

,V1_1,V1_2,V1_3,V1_4,V3_1,V3_2,V3_3,V3_4,V5_1,V5_2,V5_3,V5_4,V7_1,V7_2,V7_3,V7_4,V9_1,V9_2,V9_3,V9_4
0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0
1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0
2,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0
3,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1
4,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1

In [16]:
# Now, because the 1 (Ace) is the highest card in Poker, we should change our data accordingly:
to_change = df.iloc[:,[1,3,5,7,9]]
changed = to_change.replace(range(1,14),[13] + list(range(1,13)))  
# Ace is put on top (1 -> 13), Then everything is lowered (7->6 and 2->1 etc.)

In [17]:
prepped = changed.join(cat_1hot).join(df.iloc[:,10]) # After all column preprocessing
prepped.head()

,V2,V4,V6,V8,V10,V1_1,V1_2,V1_3,V1_4,V3_1,...,V5_4,V7_1,V7_2,V7_3,V7_4,V9_1,V9_2,V9_3,V9_4,Class
0,11,1,10,4,4,0,0,1,0,0,...,0,0,0,0,1,0,1,0,0,2
1,8,5,3,1,8,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,2
2,3,12,12,13,5,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,2
3,9,6,1,10,8,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,1
4,2,4,3,11,5,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1

In [13]:
X = prepped.iloc[:, :-1]  # Remove the ID and Class columns
Y = prepped.iloc[:, -1]

## k-NN model

In [6]:
# Use the k-NN method (up to k_max) to predict the output variable on x_test, using the training data
def predict(x_test, x_train, y_train, k_min=1, k_max=25):
    all_predictions = []
    for k in tqdm(range(k_min,k_max)):
        # Create KNN classifier
        knn = KNeighborsClassifier(n_neighbors=k,p=2)
        # Fit the classifier to the data
        knn.fit(x_train, y_train)
        # Predict on x_test
        prediction = knn.predict(x_test)
        all_predictions.append(prediction)
    return all_predictions


# Check the accuracy of given predictions on the test set y_test
def check_accuracy(y_test, predictions):
    ground_truth = y_test.to_list()
    size = len(ground_truth)
    results = []

    for predict in predictions:
        count = 0
        for i, x in enumerate(ground_truth):
            if predict[i] == ground_truth[i]:
                count += 1
        results.append(count / size)
    return results

In [7]:
# Split our training data into training and test data to find the best k

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=35)
all_predictions = predict(X_test, X_train, Y_train, 1, 25)
results = check_accuracy(Y_test, all_predictions)
print(results)
max_value = max(results)
max_index = results.index(max_value)
print("Max value:", max_value)
print("Max index:", max_index)

# Running this for 100.000 of the values (for k=1-24), we get an accuracy of 0.6145 for k=18

100%|████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:15<00:00,  1.52it/s]

[0.5095, 0.571, 0.5575, 0.581, 0.583, 0.598, 0.584, 0.598, 0.576, 0.588, 0.583, 0.587, 0.5855, 0.591, 0.598, 0.601, 0.597, 0.602, 0.6015, 0.605, 0.6045, 0.605, 0.5915, 0.601]
Max value: 0.605
Max index: 19

In [14]:
# SVM

def predict_svm(x_test, x_train, y_train):
    all_predictions = []
    svc = svm.SVC()
    svc.fit(x_train, y_train)
    prediction = svc.predict(x_test)
    all_predictions.append(prediction)
    return all_predictions


# Training the different algorithms
# for testSize in range(5,25,5):
testSize = 10
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=testSize/100, random_state=35)

# SUPPORT VECTOR MACHINES
all_predictions = predict_svm(X_test, X_train, Y_train)
results = check_accuracy(Y_test, all_predictions)
print("\nTRAINING USING SVM")
print("\nTest size = ", testSize/100)
print(results)

# This results in a accuracy of 0.5695 for 20 000 items and 0.5584 for 100 000 items

TRAINING USING SVM

Test size =  0.1
[0.5584]